### ISSUE TITLE
Scripts not working after repack

### ISSUE THREAD

**Issue by testanull** [gatlindada/awvs-decode#2]
Thanks for great works
But after trying to repack scripts, it seems that acunetix doesn't use these scripts anymore, 
After repacking, the blob size is not same as old file:
![image](https://user-images.githubusercontent.com/21060210/79088833-0b703900-7d6e-11ea-9b54-a1942fc3022f.png)
Hope you take a look at this, thanks!

**Comment by gatlindada** [comment]
I tested it on version 13.0.200205121 and it works.
Follow these steps:
1. backup:
* `cd 'C:\Program Files (x86)\Acunetix\13.0.200205121'`
* `mv wvsc_blob.bin wvsc_blob.bin.bak`
2. repack:
* `python3 awvs-repack-protoc.py`
* `cp wvsc_blob-repack.bin 'C:\Program Files (x86)\Acunetix\13.0.200205121\wvsc_blob.bin'`
3. Scan official target 'http://testphp.vulnweb.com/' to test whether it works.

ps. If you add a new script, please check the details in the task's scan log (`C:\ProgramData\Acunetix\shared\scans\{UUID}.zip\logfile.csv`) to confirm whether it has been scheduled. If it is not scheduled, please confirm that your scanning strategy includes this script. Acunetix has configured some optimized scanning strategies by default (`C:\Program Files (x86)\Acunetix\13.0.200205121\data\profiles\*.profile`)

ps. If the xml information corresponding to the new script you added does not exist in the original database, please connect to the database through ‘`C:\ProgramData\Acunetix\settings.ini`’ and add the corresponding entry.

ps. Although the change in the size of the repackaged file is caused by the different compression level settings of zlib, it will not affect the decompression.

**Comment by testanull** [comment]
Hmm, 
I did exactly what you said above
I run acunetix through both commandline and web interface
With original scripts, running logs show that it was successfully added.
But after repacking, there is no success log with new scripts.
Can you give me a sample of repacked blob for testing?

**Comment by testanull** [comment]
Here is the failed log
![image](https://user-images.githubusercontent.com/21060210/79170611-197b9380-7e1a-11ea-8ec2-f4ae7852863c.png)
And success log:
![image](https://user-images.githubusercontent.com/21060210/79170662-40d26080-7e1a-11ea-924c-3737876037d1.png)
You can see the difference between them,

**Comment by testanull** [comment]
I think the problem is the "\" character in script.name
I 'm repacking scripts on windows, so the script.name may be like this: "/lib\legacy.js" instead of "/lib/legacy.js"
![image](https://user-images.githubusercontent.com/21060210/79178355-38d0eb80-7e2f-11ea-8200-22e88d51f005.png)
After replacing "\" to "/", it works normally
Just add this and fixed
`script.name = script.name.replace("\\", "/")`

**Comment by gatlindada** [comment]
nice work!

**Comment by boluoha** [comment]
I have a question:
the awvs13,how to call google v8 engine launched  crawling the site structure?
thanks

**Comment by gatlindada** [comment]
Headless Chrome, refer to:  [https://github.com/puppeteer/puppeteer](https://github.com/puppeteer/puppeteer)
